import { redirect } from "next/navigation";
import BackLink from "@/app/components/BackLink";
import { createSupabaseAdminClient } from "@/lib/supabase/server";
import { requireAdmin } from "@/lib/services/adminAccess";
import ReportActions from "./ReportActions";

export const dynamic = "force-dynamic";
const TABLES = ["offer_images","offer_videos","service_realization_images","service_realization_videos"] as const;
export default async function AdminReportsPage(){try{await requireAdmin()}catch{redirect("/dashboard")};const supabase=createSupabaseAdminClient();const {data:reports}=await supabase.from("admin_monthly_reports").select("id,period_start,period_end,status,subject,sent_at,error_message,metrics").order("period_start",{ascending:false}).limit(24);const moderation={review:0,rejected:0,failed:0,approved:0,pending:0};for(const table of TABLES){const {data}=await supabase.from(table).select("moderation_status");for(const row of data??[]){const key=String(row.moderation_status) as keyof typeof moderation;if(key in moderation)moderation[key]++}}return <main className="koluj-home min-h-screen text-[var(--koluj-text)]"><div className="koluj-wide-frame relative z-10"><section className="koluj-hero-card p-5 md:p-8"><BackLink href="/dashboard">Dashboard</BackLink><div className="mt-7 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><h1 className="koluj-heading">Měsíční reporty</h1><p className="mt-3 text-[var(--koluj-muted)] md:text-lg">Historie manažerských reportů a aktuální stav moderace médií.</p></div><ReportActions/></div></section><section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries({"Ke kontrole":moderation.review,"Zamítnuté":moderation.rejected,"Chyby":moderation.failed,"Schválené":moderation.approved,"Čekající":moderation.pending}).map(([label,value])=><div className="koluj-card p-5" key={label}><p className="text-sm font-black text-[var(--koluj-muted)]">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>)}</section><section className="koluj-card mt-6 overflow-hidden"><div className="divide-y divide-black/5">{(reports??[]).map((report)=><article key={report.id} className="grid gap-3 p-5 md:grid-cols-[1fr_auto] md:items-center"><div><p className="font-black">{report.subject}</p><p className="mt-1 text-sm text-[var(--koluj-muted)]">{new Date(report.period_start).toLocaleDateString("cs-CZ")} – {new Date(report.period_end).toLocaleDateString("cs-CZ")}</p>{report.error_message&&<p className="mt-2 text-sm font-bold text-red-600">{report.error_message}</p>}</div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-black ${report.status==="sent"?"bg-green-100 text-green-700":report.status==="failed"?"bg-red-100 text-red-700":"bg-amber-100 text-amber-700"}`}>{report.status}</span>{report.sent_at&&<span className="text-xs text-[var(--koluj-muted)]">{new Date(report.sent_at).toLocaleString("cs-CZ")}</span>}</div></article>)}{!reports?.length&&<p className="p-10 text-center text-[var(--koluj-muted)]">Zatím nebyl vytvořen žádný report.</p>}</div></section></div></main>}
